import { UserContextProvider } from "@/contexts/user";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserContextProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </UserContextProvider>
  );
}
